# Generated by Django 5.0.9 on 2024-10-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('time_complexity', models.CharField(max_length=50)),
                ('space_complexity', models.CharField(max_length=50)),
                ('python_code', models.TextField()),
                ('algorithm_type', models.CharField(choices=[('SORT', 'Sorting'), ('SEARCH', 'Searching'), ('GRAPH', 'Graph'), ('DP', 'Dynamic Programming')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_description', models.TextField()),
                ('input_example', models.TextField()),
                ('output_example', models.TextField()),
                ('explanation', models.TextField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('visualization_data', models.JSONField(null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.algorithm')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('algorithm', 'order')},
            },
        ),
    ]
